CREATE TABLE "hashtags" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar,
                            "created_at" timestamp
);
