CREATE TABLE "projects" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar,
                            "slug" varchar,
                            "description" text,
                            "created_at" timestamp
);